spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_prod
    username: sfg_prod_user
    password: guru
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: false
